iwsc/iwsc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

admin.site.site_header = "IWSC"
admin.site.site_title = "IWSC"
admin.site.index_title = "IWSC"

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns += staticfiles_urlpatterns()

iwsc/main/urls.py
from django.urls import path
from . import views
from .views import *

from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = "main"
urlpatterns = [
	path('',views.home , name = "home"),
	path('about/' ,views.about , name = "about"),
    path('contact/', views.contact, name = "contact"), 
    path('blog/', views.blog, name='blog'), 
    
]


urlpatterns += staticfiles_urlpatterns()

iwsc/main/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

class Blog(models.Model):
	opportunity_type =  models.CharField(max_length = 50)
	description = models.TextField()
	eligibility=models.CharField(max_length = 500)
	deadline=models.CharField(max_length = 500)
	
	def __str__(self):
		return self.opportunity_type

class Contact(models.Model):
	name=models.CharField(max_length=100)
	mail=models.EmailField()
	contact_Number=PhoneNumberField()
	message=models.TextField()

	def __str__(self):
		return self.name



iwsc/main/views.py
from django.shortcuts import render, redirect
from .models import Blog 
from django.contrib import messages
from django.core.mail import send_mail
from .form import ContactForm
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.core.paginator import Page,Paginator,PageNotAnInteger,EmptyPage

def home(request):
	return render(request = request,
		 		  template_name = "home.html",
				  
				  )
def about(request):
	return render(request = request,
		 		  template_name = "about.html",
				  # context = {"blogs" : blog.objects.all}
				  )



def contact(request):
	if request.method=='POST':
		message_name = request.POST['name']
		message_email = request.POST['mail']
		# message_contact = request.POST['contact']
		message = request.POST['message']

		send_mail(
			'Message from '+message_name, #subject
			message +' Send a reply to this query at : '+message_email,  #message
			message_email ,  # from emails
			['iwsc.igdtuw@gmail.com'],
		)
		messages.info(request , message_name)
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			messages.info(request,'Thanks ,We have recieved your email and will respond shortly...') 

		else :
			messages.error(request,'Enter Correct Data') 

	form = ContactForm()
	return render(request,'contact.html',{'form':form} )
	

def blog(request):
	blogArr= Blog.objects.all()
	page = request.GET.get('page', 1)
	paginator = Paginator(blogArr, 18)
	try:
		bblog = paginator.page(page)
	except PageNotAnInteger:
		bblog = paginator.page(1)
	except EmptyPage:
		bblog = paginator.page(paginator.num_pages)
	blogArr1=Blog.objects.order_by().values('opportunity_type').distinct()
	
	opp_val = request.GET.get('role')
	city_val = request.GET.get('city')
	district_val = request.GET.get('role')
	if opp_val !='' and opp_val is not None :
		bblog = blogArr.filter(opportunity_type__icontains = opp_val)
	elif city_val !='' and city_val is not None :

		bblog = blogArr.filter(city__icontains = city_val) 

	if not blogArr :
		messages.error(request,'Currently there are 0 blogs')
	context = {
		'blogArr' : blogArr,
		'blogArr1' : blogArr1,
		'bblog' : bblog
	}
	return render(request= request, 
				  template_name = "blog.html",
				  context = context)


iwsc/main/templates/about.html
{% load static %}
<!DOCTYPE html>
<head>
    <title>IWSC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/ab6.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;900&display=swap" rel="stylesheet">
  </head>
  <body>
      <header>
      <div class="wrapper">
          <div class="logo">
            <img src="../static/img/logo.jpg" alt="">
          </div>
  <ul class="nav-area">
  <li><a href="{% url 'main:home' %}">Home</a></li>
  <li><a href="/about/">About</a></li>
  <li><a href="/blog/">Blogs</a></li>
  <li><a href="/contact/">Contact</a></li>
  </ul>
  </div>
  <div class="welcome-text">
            <div class="card text-center">
            <div class="card-header">
              <h2>What is Inception Wave?</h2>
            </div>
            <div class="card-body">
              <p class="card-text">Inception Wave is an organisation that combines the entrepreneurial innovation driven mindset of an emerging and vibrant youth community with the colossal upsides and tremendous convenience that comes with effective connection and collaboration. Our vision is to effectively enhance professional culture by enabling our users to find the people and communities there personal and professional interests align with. This is envisioned as a process that will compartmentalize and segregate online spaces on our services via parameters such as geographical location, interests, experiences and potential prospects. The idea is to present and furnish a platform where it is the users who decide their preferences and are able to come across an extensive community of like-minded people that share common aspirations and a more-or less unified outlook. Being a student-led and student-run enterprise, the key feature here is flexibility, adaptability, and dynamic feedback response.
              </p>
            </div>
            <div class="card-footer text-muted">
              <a href = "https://m.facebook.com/Inception-Wave-igdtuw-105345131339106/?refid=52&__tn__=C-R" class="fb-ic" >
                <i class="fab fa-facebook-f fa-2x"> </i>
              </a>
              <a href = "#" class="tw-ic" >
                <i class="fab fa-twitter  fa-2x"> </i>
              </a>
              <a href = "#" class="li-ic" >
                <i class="fab fa-linkedin-in  fa-2x"> </i>
              </a>
              <a href = "https://www.instagram.com/iwsc_igdtuw/" class="ins-ic" >
                <i class="fab fa-instagram  fa-2x"> </i>
              </a>
            </div>
          </div>
          <h3 class="text-center"> <b>What We Provide At <span>IWSC IGDTUW</span></b></h3>
          <div class="card-deck" >
              <div class="card border-info shadow p-3 mb-5 rounded" style="height:10rem;">
                  <i class="card-img-top fas fa-laptop fa-4x "></i>
                <div class="card-body">
                  <h5 class="card-title text-center">Internship Details</h5>
                </div>
              </div>
              <div class="card border-info shadow p-3 mb-5 rounded " style="height:10rem;">
                  <i class=" card-img-top fas fa-user-graduate fa-4x"></i>
                  <div class="card-body">
                      <h5 class="card-title text-center">Scholarship Details</h5>
                    </div>
              </div>
              <div class="card border-info shadow p-3 mb-5 rounded " style="height:10rem;">
                  <i class=" card-img-top fas fa-trophy fa-4x"></i>
                  <div class="card-body">
                      <h5 class="card-title text-center">Competition Details</h5>
                    </div>
              </div>
              <div class="card border-info shadow p-3 mb-5 rounded" style="height:10rem;">
                  <i class=" card-img-top fas fa-business-time fa-4x"></i>
                  <div class="card-body">
                    <h5 class="card-title text-center">Career Oriented Hap</h5>
                  </div>
              </div>
  
          </div>
          <div>
          <center>
            
                <a class="btn btn-primary text-white"  href="/blog/">View All Opportunities</a>
          </center>
        </div> 
      </div>
  </header>
  </body>
  </html>

iwsc/main/templates/blog.html
{% load static %}

<!DOCTYPE html>
<head>
    <title>IWSC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/blg.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    </head>
<body>

    <header>
      <div class="wrapper">
        <div class="logo">
          <img src="../static/img/logo.jpg" alt="">
        </div>
<ul class="nav-area">
<li><a href="{% url 'main:home' %}">Home</a></li>
<li><a href="/about/">About</a></li>
<li><a href="/blog/">Blogs</a></li>
<li><a href="/contact/">Contact</a></li>
</ul>
</div>
</header>

<section>
    <div class="search-blog text-center">
	 {% if messages%}
        {% for m in messages %}
         <h1 class="text-white"> {{m}}</h1>
        {% endfor %}
      {% else %}
        
        <form action="/blog/" method="get" id ="findform">
        <div class="form-group">
        <select class="form-control" id="sel1" name="role">
            <option disabled selected>Opportunity Type</option>
            {% for opp in blogArr1 %}
            <option>{{opp.opportunity_type}}</option>
            {% endfor %}
        </select>
        <button type="submit" class="btn btn-primary " onclick="submitForm()"> Search</button>
      </form>
        </div>
	    {% endif %}
        </div>
</section>
	
    <section>     
        <div class="container">
            <div class="row blog_row">
                <div class="col">
                    <div class="blog_container item_grid">
            {% for opp in bblog %}
            <div class="blog_item">
            <div class="card">
              <div class="card-header" style="background-image : linear-gradient(to right,#5b9eda,#ccd9ff); "></div>
                <div class="card-body">
                    <h4 class="card-title job-title"><b>{{opp.opportunity_type}}</b></h4>
                        <p class="card-text"> 
                          <i class="fas fa-pencil-alt text-muted"></i>&NonBreakingSpace;{{ opp.description }}<br>
                          <i class="fas fa-user text-muted"></i>&NonBreakingSpace;{{opp.eligibility}}<br>
                          <i class="fas fa-clock text-muted"></i>&NonBreakingSpace;{{opp.deadline}} <br>
                   <i class="fas fa-arrow text-muted"></i>&NonBreakingSpace;<a>{{opp.apply}}</a> <br>
                  
                        </p>
                </div>
                <div class="card-footer text-muted text-center" >
    
                  <a href = "https://m.facebook.com/Inception-Wave-igdtuw-105345131339106/?refid=52&__tn__=C-R" class="fb-ic" >
                    <i class="fab fa-facebook-f "> </i>
                  </a>
                  <a href = "#" class="tw-ic" >
                    <i class="fab fa-twitter "> </i>
                  </a>
                  <a href = "#" class="li-ic" >
                    <i class="fab fa-linkedin-in "> </i>
                  </a>
                  <a href = "https://www.instagram.com/iwsc_igdtuw/" class="ins-ic" >
                    <i class="fab fa-instagram "> </i>
                  </a>
                </div>
               
                
            </div>
        </div> 
        {% endfor %}
        </div>
    </div>
</div>
</div>
</section>  
        </div>
    </div>
    <div style="float: right;" >
    {% if bblog.has_other_pages %}
  <ul class="pagination pagelink text-center">
    {% if bblog.has_previous %}
      <li><a href="?page={{ bblog.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled" ><span>&laquo;</span></li>
    {% endif %}
    {% for i in bblog.paginator.page_range %}
      {% if bblog.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if bblog.has_next %}
      <li><a href="?page={{ bblog.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</div>

</body>
</html>

iwsc/main/templates/contact.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<head>
    <title>IWSC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/contact.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
    <div class="wrapper">
        <div class="logo">
          <img src="../static/img/logo.jpg" alt="">
        </div>
<ul class="nav-area">
<li><a href="{% url 'main:home' %}">Home</a></li>
<li><a href="/about/">About</a></li>
<li><a href="/blog/">Blogs</a></li>
<li><a href="/contact/">Contact</a></li>
</ul>
</div>
<div class="welcome-text">
  <div class="card ">
    <div class="card-header text-center">
      <h2>
        <a href="mailto:iwsc.igdtuw@gmail.com">
          <i class="fas fa-envelope fa-2x"></i>
        </a>
        <a href = "https://m.facebook.com/Inception-Wave-igdtuw-105345131339106/?refid=52&__tn__=C-R" class="fb-ic" >
        <i class="fab fa-facebook-f  fa-2x"> </i>
      </a>
      <a href = "#" class="tw-ic" >
        <i class="fab fa-twitter   fa-2x"> </i>
      </a>
      <a href = "#" class="li-ic" >
        <i class="fab fa-linkedin-in   fa-2x"> </i>
      </a>
      <a href = "https://www.instagram.com/iwsc_igdtuw/" class="ins-ic" >
        <i class="fab fa-instagram fa-lg  fa-2x"> </i>
      </a></h2>
    </div>
    <div class="card-body">
      <p class="card-text">
        <div class=" text-center">
      {% for m in messages %}
        {{m}}
      {% endfor %}
    </div>
      <div class="form-group pl-3">
        <form class=" cont" method="POST">
          {%csrf_token%}      
          {{form | crispy}}
          <button type="submit"   class="btn btn-primary text-white">Submit</button>
        </form>
      </div>      
    </p>
    </div>
    <div class="card-footer text-muted text-center">
      <a href="mailto:iwsc.igdtuw@gmail.com"><i class="fas fa-envelope fa-3x">iwsc.igdtuw@gmail.com</i> </a>
    </div>
  </div>
    </div>
</header>
</body>
</html>

iwsc/main/templates/home.html
{% load static %}

<!DOCTYPE html>
<head>
    <title>IWSC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
    <div class="wrapper">
        <div class="logo">
            <img src="../static/img/logo.jpg" alt="">
        </div>
<ul class="nav-area">
<li><a href="{% url 'main:home' %}">Home</a></li>
<li><a href="/about/">About</a></li>
<li><a href="/blog/">Blogs</a></li>
<li><a href="/contact/">Contact</a></li>
</ul>
</div>
<div class="welcome-text">
        <h1>Inception Wave Student Chapter <span>IGDTUW</span></h1>
        <a href = "https://m.facebook.com/Inception-Wave-igdtuw-105345131339106/?refid=52&__tn__=C-R" class="fb-ic" >
          <i class="fab fa-facebook-f  fa-2x"> </i>
        </a>
        <a href = "#" class="tw-ic" >
          <i class="fab fa-twitter  fa-2x"> </i>
        </a>
        <a href = "#" class="li-ic" >
          <i class="fab fa-linkedin-in  fa-2x"> </i>
        </a>
        <a href = "https://www.instagram.com/iwsc_igdtuw/" class="ins-ic" >
          <i class="fab fa-instagram  fa-2x"> </i>
        </a>
    </div>
</header>
</body>
</html>